//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hieu_TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANH_MUC
    {
        public long MA_DM { get; set; }
        public string TEN_DM { get; set; }
    }
}
