//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hieu_TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINH_ANH
    {
        public int ID { get; set; }
        public string HINH { get; set; }
        public long MA_SACH { get; set; }
    }
}
