//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hieu_TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_DON
    {
        public long MA_HD { get; set; }
        public string USERNAME { get; set; }
        public int IDTT { get; set; }
        public string DIA_CHI { get; set; }
        public string HO_TEN { get; set; }
        public Nullable<long> DIEN_THOAI { get; set; }
        public Nullable<System.DateTime> NGAYDATHANG { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<long> TONG_TIEN { get; set; }
    }
}
