//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hieu_TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOI_DUNG
    {
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public long IDQH { get; set; }
        public Nullable<int> XACTHUC { get; set; }
        public string BARCODE { get; set; }
        public string EMAIL { get; set; }
        public string HO_TEN { get; set; }
        public string DIA_CHI { get; set; }
    }
}
