//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hieu_TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHA_XUAT_BAN
    {
        public long MA_NXB { get; set; }
        public string TEN_NXB { get; set; }
    }
}
