//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hieu_TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVINCE
    {
        public PROVINCE()
        {
            this.DISTRICTs = new HashSet<DISTRICT>();
        }
    
        public string PROVINCEID { get; set; }
        public string NAME { get; set; }
        public string TYPE { get; set; }
    
        public virtual ICollection<DISTRICT> DISTRICTs { get; set; }
    }
}
