//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hieu_TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public long MA_SACH { get; set; }
        public long MA_DM { get; set; }
        public long MA_NXB { get; set; }
        public string TEN_SACH { get; set; }
        public Nullable<long> GIA_BIA { get; set; }
        public Nullable<long> GIA_BAN { get; set; }
        public Nullable<System.DateTime> NGAY_NHAP { get; set; }
        public Nullable<long> SOLUOTMUA { get; set; }
        public string ANHBIA { get; set; }
        public Nullable<int> TINHTRANG { get; set; }
        public Nullable<long> LUOT_XEM { get; set; }
    }
}
