//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hieu_TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLIDER
    {
        public int ID { get; set; }
        public string HINH { get; set; }
        public string TITLE { get; set; }
        public string BODY { get; set; }
    }
}
