//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hieu_TMDT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wthEntities : DbContext
    {
        public wthEntities()
            : base("name=wthEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<CT_HOA_DON> CT_HOA_DON { get; set; }
        public DbSet<DANH_MUC> DANH_MUC { get; set; }
        public DbSet<DISTRICT> DISTRICTs { get; set; }
        public DbSet<HINH_ANH> HINH_ANH { get; set; }
        public DbSet<HOA_DON> HOA_DON { get; set; }
        public DbSet<NGUOI_DUNG> NGUOI_DUNG { get; set; }
        public DbSet<NHA_XUAT_BAN> NHA_XUAT_BAN { get; set; }
        public DbSet<PROVINCE> PROVINCEs { get; set; }
        public DbSet<SACH> SACHes { get; set; }
        public DbSet<SLIDER> SLIDERs { get; set; }
        public DbSet<WARD> WARDs { get; set; }
    }
}
